server:
  addr: ":8081"
  readTimeOut: 30
  writeTimeOut: 30
  maxHeaderBytes: 1048576
logger:
  logLevel: debug
  logPath: "../error/error.log"
  maxSize: 128
  maxAge: 7
  maxBackups: 30
  compress: false
databases:
  "alimatch/modadmin":
    driver: mysql
    default: root:server123&*(@tcp(192.168.2.118:3306)/modadmin?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    idleConns: 10 
    openConns: 15
    idleTimeout: 300
    aliveTimeout: 300
    cluster: false
    sources:
      - root:server123&*(@tcp(192.168.2.118:3306)/modadmin?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    replicas:
      - root:server123&*(@tcp(192.168.2.118:3306)/modadmin?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
cache:
  redis:
    addr: 192.168.2.118:6379
    password: Baison789321
    db: 0
    protocol: 3
    dialTimeout: 30
    readTimeOut: 300
    writeTimeOut: 300
    poolSize: 16
    idleConns: 8
locker:
  redis:
    addr: 192.168.2.118:6379
    password: Baison789321
    db: 0
    protocol: 3
    dialTimeout: 30
    readTimeOut: 300
    writeTimeOut: 300
